drop type public.app_role;
create type public.app_role as enum(
  'admin',
  'board_member',
  'code_of_conduct_coordinator',
  'key_member',
  'member',
  'membership_coordinator',
  'prospective_member',
  'voting_coordinator',
  'voting_member'
);
--
drop type public.app_permission;
create type public.app_permission as enum(
  'new.can_apply',
  'member.can_comment',
  'member.can_vote',
  'voting.can_view_all_comments',
  'admin.can_view_dues',
  'admin.can_add_membership_note',
  'admin.can_approve_sponsorship'
);
--
create table public.user_roles (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  role app_role not null,
  unique (user_id, role)
) TABLESPACE pg_default;

create table public.role_permissions (
  id bigint generated by default as identity primary key,
  role app_role not null,
  permission app_permission not null,
  unique (role, permission)
) TABLESPACE pg_default;

create or replace function public.modify_role_permissions(
    role_name app_role,
    permission_name app_permission
)
returns void as $$
begin
  INSERT INTO public.role_permissions (role, permission)
  VALUES (role_name, permission_name)
  ON CONFLICT (role, permission) DO NOTHING;
end;
$$ language plpgsql;

DROP TABLE IF EXISTS public.role_permissions_log;
create table public.role_permissions_log (
    log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_current text not null,
    user_session text not null,
    changed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    operation TEXT NOT NULL,
    old_role app_role,
    old_permission app_permission,
    new_role app_role,
    new_permission app_permission
);

create or replace function public.log_role_permissions_changes()
returns TRIGGER as $$
declare
    -- A variable to hold the user ID, which can be passed from your app or a session variable
    -- For example, if you use Supabase, this is how you'd get the authenticated user's ID
    current_user_id UUID := auth.uid();
begin
    if TG_OP = 'INSERT' then
        insert into public.role_permissions_log (
            user_current, user_session, operation, new_role, new_permission
        )
        values (
            CURRENT_USER::text, SESSION_USER::text,
            TG_OP,
            NEW.role,
            NEW.permission
        );
        return NEW;
    elsif TG_OP = 'UPDATE' then
        insert into public.role_permissions_log (
            user_current, user_session, operation, old_role, old_permission, new_role, new_permission
        )
        values (
            CURRENT_USER::text, SESSION_USER::text,
            TG_OP,
            OLD.role,
            OLD.permission,
            NEW.role,
            NEW.permission
        );
        return NEW;
    elsif TG_OP = 'DELETE' then
        insert into public.role_permissions_log (
            user_current, user_session, operation, old_role, old_permission
        )
        values (
            CURRENT_USER::text, SESSION_USER::text,
            TG_OP,
            OLD.role,
            OLD.permission
        );
        return OLD;
    end if;
end;
$$ LANGUAGE plpgsql;

create trigger role_permissions_changes_trigger
after insert or update or delete on public.role_permissions
for each row execute function public.log_role_permissions_changes();

insert into public.role_permissions (role, permission)
values 
('prospective_member', 'new.can_apply'),
('member', 'member.can_view_profile'),
('member', 'member.can_view_home'),
('member', 'member.can_vote'),
('member', 'member.can_comment'),
('voting_member', 'voting.can_view_all_comments'),
('admin', 'admin.can_view_dues'),
('admin', 'admin.can_add_membership_note'),
('admin', 'admin.can_approve_sponsorship');

create view user_role_view as 
  select 
  from
    pubic.user_roles
  left join public.role_permissions ON public.user_roles.role = public.role_permissions.role
;