create table public.profile (
  user_id uuid not null default auth.uid (),
  created_at timestamp with time zone not null default now(),
  last_modified timestamp with time zone not null default now(),
  display_name text null,
  pronounceable_name text null,
  pronouns text null,
  email_display text null,
  email_google text null,
  email_gravatar text null,
  social_twitter text null,
  social_facebook text null,
  social_website text null,
  social_linkedin text null,
  social_blog text null,
  summary text null,
  reasons text null,
  projects text null,
  skills text null,
  public_reasons boolean null,
  public_projects boolean null,
  public_skills boolean null,
  public_member boolean null,
  constraint profile_pkey primary key (user_id),
  constraint profile_user_id_key unique (user_id),
  constraint profile_user_id_fkey foreign KEY (user_id) references auth.users (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;
